
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: digitaltwin-platform-viewer
  name: marklong-demo
spec:
  selector:
    matchLabels:
      app: marklong-demo
  template:
    metadata:
      namespace: marklong-learning
      labels:
        app: marklong-demo
    spec:
      imagePullSecrets:
        - name: ali-secret
      containers:
      - name: marklong-demo
        image: registry.cn-shanghai.aliyuncs.com/marklong-learning/marklong-test:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: marklong-learning
  name: marklong-demo-service
spec:
  selector:
    app: marklong-demo
  ports:
  - port: 3000
    targetPort: 80
  type: NodePort